"""add market timer field

Revision ID: 03001043e4d6
Revises: 17de7be96b95
Create Date: 2025-06-18 07:31:17.203452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '03001043e4d6'
down_revision: Union[str, None] = '17de7be96b95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('market_timer_end', sa.DateTime(), nullable=True))
    op.drop_column('users', 'last_daily')
    op.drop_column('users', 'tg_reward_claimed')
    op.drop_column('users', 'tg_timer_started')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tg_timer_started', mysql.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('tg_reward_claimed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_daily', mysql.DATETIME(), nullable=True))
    op.drop_column('users', 'market_timer_end')
    # ### end Alembic commands ###
