"""fix market_timer_end type

Revision ID: 0639b959af64
Revises: 200bb53bebcb
Create Date: 2025-06-18 09:00:56.139368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0639b959af64'
down_revision: Union[str, None] = '200bb53bebcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'seconds_left')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('seconds_left', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
