"""add role field to user

Revision ID: 17de7be96b95
Revises: 2bf3782e27d3
Create Date: 2025-06-18 04:34:27.826495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '17de7be96b95'
down_revision: Union[str, None] = '2bf3782e27d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=False))
    op.drop_column('users', 'tg_timer_started')
    op.drop_column('users', 'tg_reward_claimed')
    op.drop_column('users', 'last_daily')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_daily', mysql.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('tg_reward_claimed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('tg_timer_started', mysql.DATETIME(), nullable=True))
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
