"""Add referral_reward_claimed with correct types

Revision ID: 2062d72a632b
Revises: 4c6268351820
Create Date: 2025-06-13 02:02:04.817131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2062d72a632b'
down_revision: Union[str, None] = '4c6268351820'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quests', 'title',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.drop_index(op.f('referral_code'), table_name='users')
    op.drop_column('users', 'boost_expiry')
    op.drop_column('users', 'referral_count')
    op.drop_column('users', 'referral_reward_claimed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referral_reward_claimed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('referral_count', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('boost_expiry', mysql.DATETIME(), nullable=True))
    op.create_index(op.f('referral_code'), 'users', ['referral_code'], unique=True)
    op.alter_column('quests', 'title',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
