"""Replace game balances with tank games

Revision ID: 48515c4f4ead
Revises: ab6a43dd340d
Create Date: 2025-07-05 17:38:03.998211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '48515c4f4ead'
down_revision: Union[str, None] = 'ab6a43dd340d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exchange_rates', 'from_currency',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('exchange_rates', 'to_currency',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('exchange_requests', 'from_currency',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('exchange_requests', 'to_currency',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.add_column('users', sa.Column('tanki_blitz_balance', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('mir_tankov_balance', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('wot_blitz_balance', sa.Integer(), nullable=False))
    op.drop_column('users', 'zenless_balance')
    op.drop_column('users', 'honkai_balance')
    op.drop_column('users', 'genshin_balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('genshin_balance', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('honkai_balance', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('zenless_balance', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('users', 'wot_blitz_balance')
    op.drop_column('users', 'mir_tankov_balance')
    op.drop_column('users', 'tanki_blitz_balance')
    op.alter_column('exchange_requests', 'to_currency',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('exchange_requests', 'from_currency',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('exchange_rates', 'to_currency',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('exchange_rates', 'from_currency',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###
