"""Initial tables

Revision ID: 4c6268351820
Revises: 
Create Date: 2025-06-11 07:59:33.704249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c6268351820'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promocodes',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('reward_type', sa.String(length=20), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('quests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('quest_type', sa.String(length=20), nullable=True),
    sa.Column('reward_type', sa.String(length=20), nullable=True),
    sa.Column('reward_value', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('max_energy', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('referral_code', sa.String(length=16), nullable=True))
    op.add_column('users', sa.Column('referred_by', sa.String(length=16), nullable=True))
    op.add_column('users', sa.Column('referral_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('boost_expiry', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_daily', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_unique_constraint(None, 'users', ['referral_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=False)
    op.drop_column('users', 'last_daily')
    op.drop_column('users', 'boost_expiry')
    op.drop_column('users', 'referral_count')
    op.drop_column('users', 'referred_by')
    op.drop_column('users', 'referral_code')
    op.drop_column('users', 'max_energy')
    op.drop_table('quests')
    op.drop_table('promocodes')
    # ### end Alembic commands ###
