"""add daily streak fields

Revision ID: 5342d848cb6b
Revises: 97521a0ea366
Create Date: 2025-06-17 05:11:56.388262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5342d848cb6b'
down_revision: Union[str, None] = '97521a0ea366'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'coins',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('users', 'energy',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('users', 'max_energy',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('users', 'level',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('users', 'total_clicks',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('users', 'referral_code',
               existing_type=mysql.VARCHAR(length=16),
               nullable=False)
    op.alter_column('users', 'milestone_5_friends_claimed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('users', 'reward_5_friends_claimed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'reward_10_friends_claimed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'youtube_subscribed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('users', 'youtube_reward_claimed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'telegram_subscribed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('users', 'telegram_reward_claimed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'boost_multiplier',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('users', 'last_energy_update',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_unique_constraint(None, 'users', ['referral_code'])
    op.drop_column('users', 'tg_timer_started')
    op.drop_column('users', 'tg_reward_claimed')
    op.drop_column('users', 'last_daily')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_daily', mysql.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('tg_reward_claimed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('tg_timer_started', mysql.DATETIME(), nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'last_energy_update',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'boost_multiplier',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('users', 'telegram_reward_claimed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'telegram_subscribed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('users', 'youtube_reward_claimed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'youtube_subscribed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('users', 'reward_10_friends_claimed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'reward_5_friends_claimed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'milestone_5_friends_claimed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('users', 'referral_code',
               existing_type=mysql.VARCHAR(length=16),
               nullable=True)
    op.alter_column('users', 'total_clicks',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('users', 'level',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('users', 'max_energy',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('users', 'energy',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('users', 'coins',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
