"""change_coins_to_bigint

Revision ID: 5ce6dc0bf46c
Revises: ab39ebd93cef
Create Date: 2025-06-19 16:48:16.371302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5ce6dc0bf46c'
down_revision: Union[str, None] = 'ab39ebd93cef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'coins',
               existing_type=mysql.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'coins',
               existing_type=mysql.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
