"""add_uid_to_exchange_requests

Revision ID: 7f346698ca3d
Revises: 07bd544820b3
Create Date: 2025-06-19 17:09:07.592451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f346698ca3d'
down_revision: Union[str, None] = '07bd544820b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange_requests', sa.Column('uid', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exchange_requests', 'uid')
    # ### end Alembic commands ###
