"""add_multicurrency_support

Revision ID: 89060b1ff0f1
Revises: c6a5186816cb
Create Date: 2025-06-19 14:44:29.668899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89060b1ff0f1'
down_revision: Union[str, None] = 'c6a5186816cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('genshin_balance', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('honkai_balance', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('zenless_balance', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'zenless_balance')
    op.drop_column('users', 'honkai_balance')
    op.drop_column('users', 'genshin_balance')
    # ### end Alembic commands ###
