"""remove market_timer_end

Revision ID: 9275bdad157e
Revises: 0639b959af64
Create Date: 2025-06-18 09:10:56.974176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9275bdad157e'
down_revision: Union[str, None] = '0639b959af64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'market_timer_end')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('market_timer_end', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
