"""Add tg_timer and reward flag to User

Revision ID: 97521a0ea366
Revises: ebf08581de14
Create Date: 2025-06-16 06:31:48.202033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '97521a0ea366'
down_revision: Union[str, None] = 'ebf08581de14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tg_timer_started', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('tg_reward_claimed', sa.Boolean(), nullable=True))
    op.drop_column('users', 'tg_subscribed')
    op.drop_column('users', 'tg_subscribe_checked')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tg_subscribe_checked', mysql.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('tg_subscribed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('users', 'tg_reward_claimed')
    op.drop_column('users', 'tg_timer_started')
    # ### end Alembic commands ###
