"""fix daily streak fields

Revision ID: a4cc6efd4d34
Revises: d3ce51f26382
Create Date: 2025-06-17 05:26:15.661802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4cc6efd4d34'
down_revision: Union[str, None] = 'd3ce51f26382'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('daily_streak', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('last_daily_login', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_daily_login')
    op.drop_column('users', 'daily_streak')
    # ### end Alembic commands ###
