"""fix_locked_coins_default

Revision ID: f39deb53bf5c
Revises: 7f346698ca3d
Create Date: 2025-06-19 17:12:25.248631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f39deb53bf5c'
down_revision: Union[str, None] = '7f346698ca3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'locked_coins',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'locked_coins',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
